false_positives = [
  "is empty",
  "Invalid",
  "Expected",
  "Unsupported",
  "JP2 output requires libvips",
  "Missing output file path",
  "Only gaussian noise is supported at the moment",
]

skip_endpoints = [
  "Sharp.cork",
  "Sharp.uncork",
  "Sharp.write",
  "Sharp.on",
  "Sharp.off",
  "Sharp.once",
  "Sharp.read",
  "Sharp.pipe",
  "Sharp.unpipe",
  "Sharp.addListener",
  "Sharp.removeListener",
  "Sharp.removeAllListeners",
  "Sharp.pause",
  "Sharp.resume",
  "Sharp.wrap",
  "Sharp.iterator",
  "Sharp.filter",
  "Sharp.drop",
  "Sharp.flatMap",
  "Sharp.push",
  "Sharp.unshift",
  "Sharp.end",
  "Sharp.emit",
  "Sharp.toArray",
]
