[package]
name = "metrics"
version = "0.1.9"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
serde = "1.0.216"
serde_json = "1.0.134"
chrono = "0.4.42"
anyhow = { workspace = true }
rusqlite = "0.37.0"
