[package]
name = "metrics"
version = "0.1.9"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
duckdb = { version = "1.3.2", features = ["bundled"] }
serde = "1.0.216"
serde_json = "1.0.134"
anyhow = { workspace = true }
chrono = "0.4.42"
