[graph]
all-features = false
no-default-features = false

[licenses]
allow = [
    "MIT",
    "ISC",
    "Apache-2.0",
    "Zlib",
    "BSL-1.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "Unicode-3.0",
    "AGPL-3.0-or-later",
    "CC0-1.0",
]
confidence-threshold = 0.8

[licenses.private]
ignore = false

[bans]
multiple-versions = "allow"
allow-wildcard-paths = true

[advisories]
unmaintained = "workspace"
