const { makeInvalidErrorMessageOracle } = require("@railcar/support");

module.exports = {
    instrumentFilter: (f) => f.includes("js-yaml"),
    oracle: makeInvalidErrorMessageOracle([
        "is removed in js-yaml 4",
        "Unknown",
        "unknown",
        "undeclared",
        "unidentified",
        "unexpected",
        "unacceptable",
        "bad indentation",
        "is not allowed",
        "is not supported",
        "are not supported",
        "ill-formed",
        "malformed",
        "cannot contain",
        "must contain",
        "should not have",
        "can not read",
        "cannot resolve",
        "must not be",
        "may not be",
        "should be",
        "must be",
        "must not be used",
        "is expected",
        "is not allowed",
        "duplication of",
        "duplicated mapping key",
        "Specified list of YAML types",
        "tag resolver accepts not",
        "YAML directive accepts exactly one argument",
        "TAG directive accepts exactly two arguments",
        "there is a previously declared suffix",
        "the stream contains non-printable characters",
        "Multi tags can only be listed as explicit",
        "missed comma between flow collection entries",
        "expected a single document in the stream, but found more",
        "expected hexadecimal character",
        "expected valid JSON character",
        "expected the node content",
        "bad explicit indentation width",
        "repeat of a chomping mode identifier",
        "repeat of an indentation width identifier",
        "bad indentation",
        "incomplete explicit mapping pair",
    ]),
};
