false_positives = [
  "need dictionary",
  "stream error",
  "buffer error",
  "data error",
  "invalid",
  "incorrect",
  "unknown",
  "header crc mismatch",
  "too many length or distance symbols",
]
