const { makeInvalidErrorMessageOracle } = require("@railcar/support");

module.exports = {
    instrumentFilter: (f) => f.includes("fast-xml-parser"),
    oracle: makeInvalidErrorMessageOracle([
        "Cannot read properties",
        "Invalid",
        "Unclosed",
        "Unexpected",
        "is not closed",
        "is not expected",
        "is not allowed",
        "is not permitted",
        "is an invalid name",
        "are not supported",
        "Start tag expected",
        "Expected closing tag",
        "An entity must be set without",
        "Entity value can't have",
        "boolean attribute",
        "Multiple possible root nodes found",
        "Extra text at the end",
        "has not been opened",
        "Attribute",
        "Attributes",
        "Closing tag",
        "XML data is accepted in String or Bytes[] form.",
        "XML declaration allowed only at the start of the document",
        "Unpaired tag can not",
    ]),
};
