false_positives = [
  "does not exist",
  "illegal",
  "invalid",
  "must be",
  "duplicate",
  "no such",
  "is not a member of",
  "JSON at position",  # passes input string to JSON.parse()
]

skip_endpoints = [
  "fetch",
  "util.fetch",
  "Root.fetch",
  "Root.load",
  "load",
  "rpc.Service.rpcCall",
  "util.asPromise",
]
